default_stages: [pre-commit]
repos:
  # Black (formatter)
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  # Ruff (linter + import sorting)
  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #  rev: v0.6.9
  #  hooks:
  #    - id: ruff
  #      args: [--fix] # autofix where possible
  #    - id: ruff-format

  # Prettier for non-Python text files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        files: \.(yaml|yml|json|md|toml)$
        language_version: system # Use the system's node
        additional_dependencies:
          - prettier@3.6.2

  #
  - repo: local
    hooks:
      # - id: nfcore-lint
      #   name: nf-core lint
      #   entry: nf-core pipelines lint
      #   language: system
      #   pass_filenames: false
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ["--rcfile=.pylintrc"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: |
          (?x)^(
              .*ro-crate-metadata.json$|
              modules/nf-core/.*|
              subworkflows/nf-core/.*|
              .*\.snap$
          )$
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
              .*ro-crate-metadata.json$|
              modules/nf-core/.*|
              subworkflows/nf-core/.*|
              .*\.snap$
          )$
